version: "3"

services:
  cache:
    image: "redis:latest"
    expose:
      - 6379

  nginx:
    build: ./operations/nginx
    ports:
      - "81:80"
    depends_on:
      - app

  db:
    image: "postgres:latest"
    expose:
      - 5432
    env_file:
      - env.local
    volumes:
      - pgdata:/var/lob/postgresql/data

  app:
    image: "smartavi-po-tracking-app:dev"
    build:
      dockerfile: operations/Dockerfile
      context: .
    expose:
      - "8000"
    volumes:
      - .:/opt:z
    env_file:
      - env.local
    links:
      - db
      - cache

  pg_backups:
    container_name: backup
    image: "prodrigestivill/postgres-backup-local"
    restart: always
    volumes:
      - ./backup:/backups
    links:
      - db:db
    depends_on:
      - db
    env_file:
      - env.local
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_EXTRA_OPTS=-Z9 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=2
      - BACKUP_KEEP_MONTHS=1

volumes:
  pgdata:
