# Generated by Django 4.2.3 on 2023-07-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase_orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="description",
        ),
        migrations.AddField(
            model_name="purchaseorderitem",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
